### ISSUE TITLE
Help: Invalid reference when running action

### ISSUE THREAD

**Issue by ABDreos** [mislav/bump-homebrew-formula-action#171]
When running the action I have created, defined as following:
```Yaml
      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: bragir
          formula-path: Formula/bragir.rb
          homebrew-tap: ArjanCodes/homebrew-core
          base-branch: main
          download-url: https://github.com/ArjanCodes/bragir/releases/download/${{ steps.versioning.outputs.tag-name }}/bragir-${{steps.versioning.outputs.version}}.tar.gz
          commit-message: bragir ${{steps.versioning.outputs.version}}
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
```

I get back:
`Error: invalid ref: refs/heads/update-homebrew-bump-pipeline`

update-homebrew-bump-pipeline is the current branch I am working on.

Any suggestions?
