### ISSUE TITLE
Add push-to-fork for teamwork

### ISSUE THREAD

**Issue by codefromthecrypt** [mislav/bump-homebrew-formula-action#20]
Similar to peter-evans/create-pull-request push-to-fork, I would love to see the same feature here, so that when a PR is raised it is off a shared fork instead of whoever's the token is from.

**Comment by mislav** [comment]
Can you be more specific, sorry? 

> so that when a PR is raised it is off a shared fork

Can you define a "shared fork"?

**Comment by codefromthecrypt** [comment]
sure. for example, I would like the pull request to originate from tetratelabs/homebrew-core, not codefromthecrypt/homebrew-core.

while a different project, here's how I do this for winget. particularly here it is the 'push-to-fork' option that switches the fork used for the PR

```
  # This job downloads the func-e.msi from the corresponding release. It extracts properties from
  # it in order to create a winget package manifest. Finally, it creates a pull request to add the
  # new version. The pull request is a branch on tetratelabs/winget-pkgs so that anyone on the team
  # can edit it as necessary.
  msi:
    name: "microsoft/winget-create"
    runs-on: ubuntu-latest
    steps:
      # ubuntu is missing msitools https://github.com/actions/virtual-environments/issues/3857
      - name: "Install GNOME msitools"
        run: sudo apt update -qq && sudo apt install -qq -y msitools

      - name: "Checkout func-e"
        uses: actions/checkout@v2
        with:
          path: func-e

      - name: "Checkout winget-pkgs"
        uses: actions/checkout@v2
        with:
          repository: microsoft/winget-pkgs
          ref: master
          path: winget-pkgs

      - name: "Write winget manifest"
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          version=${tag#v}
          echo "MSI_VERSION=${version}" >> $GITHUB_ENV
          cd func-e
          gh release download "${tag}" -p '*windows_amd64.msi'
          manifest_path=../winget-pkgs/manifests/t/Tetrate/func-e/${version}/Tetrate.func-e.yaml
          mkdir -p $(dirname ${manifest_path})
          ./packaging/msi/winget_manifest.sh ${version} *windows_amd64.msi > ${manifest_path}
        env:  # See env section for notes on PACKAGE_BUMP_TOKEN
          GITHUB_TOKEN: ${{ secrets.PACKAGE_BUMP_TOKEN }}

      - name: "Create winget-pkgs pull request"
        uses: peter-evans/create-pull-request@v3
        id: winget-pkgs-pr
        with:
          path: winget-pkgs
          branch: func-e-${{ env.MSI_VERSION }}
          delete-branch: true
          push-to-fork: tetratelabs/winget-pkgs
          commit-message: "New version: Tetrate.func-e version ${{ env.MSI_VERSION }}"
          committer: ${{ env.GIT_COMMITTER }}
          author: ${{ env.GIT_COMMITTER }}
          title: "New version: Tetrate.func-e version ${{ env.MSI_VERSION }}"
          body: |
            - [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
            - [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
            - [x] Have you validated your manifest locally with `winget validate --manifest <path>`?
            - [x] Have you tested your manifest locally with `winget install --manifest <path>`?
            - [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?
          token: ${{ secrets.PACKAGE_BUMP_TOKEN }}

      - name: "Echo winget-pkgs pull request"
        run: |
          echo ${{ steps.winget-pkgs-pr.outputs.pull-request-url }}

```
