### ISSUE TITLE
Get a 404 on tap repo

### ISSUE THREAD

**Issue by on3iro** [mislav/bump-homebrew-formula-action#21]
Hi,

I just tried this action, but unfortunately am unable to make it work.

Here's what my workflow looks like:

```yml
# ...some more steps
      - name: Extract version
        id: extract-version
        run: |
          printf "::set-output name=%s::%s\n" tag-name "${GITHUB_REF#refs/tags/}"
      - name: Update Homebrew formula
        uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-name: crow
          formula-path: Formula/crow.rb
          homebrew-tap: sandstorm/homebrew-crow
          download-url: https://github.com/sandstorm/crow/releases/download/${{ steps.extract-version.outputs.tag-name }}/crow.tar.gz
          base-branch: main
        env:
          COMMITTER_TOKEN: ${{ secrets.CROW_TAP_TOKEN }}

```

The error I get is a 404:

```
 with:
    formula-name: crow
    formula-path: Formula/crow.rb
    homebrew-tap: sandstorm/homebrew-crow
    download-url: https://github.com/sandstorm/crow/releases/download/v0.1.0-beta-12/crow.tar.gz
    base-branch: main
    commit-message: {{formulaName}} {{version}}
  
  Created by https://github.com/mislav/bump-homebrew-formula-action
  
  env:
    COMMITTER_TOKEN: ***
GET /repos/sandstorm/crow/releases/tags/v0.1.0-beta-12 - 200 in 205ms
GET /repos/sandstorm/crow/releases/assets/49323433 - 302 in 156ms
GET /repos/sandstorm/homebrew-crow - 404 in 125ms
```

However the tap repository does exist: https://github.com/sandstorm/homebrew-crow

Any idea what I could be doing wrong here?

Thanks in advance!
