### ISSUE TITLE
Update formulat that uses git?

### ISSUE THREAD

**Issue by makeworld-the-better-one** [mislav/bump-homebrew-formula-action#22]
Would it be possible for this action to work with this kind of Formula?

https://github.com/Homebrew/homebrew-core/pull/90700

See the original commit made by the action, and then the change made by me.

**Comment by mislav** [comment]
Yes it can: set the `download-url` in your workflow configuration to `https://github.com/makeworld-the-better-one/amfora.git` instead of to the tarball. This action will then update the `tag` and `revision` fields 👍

**Comment by makeworld-the-better-one** [comment]
@mislav I tried that and still had issues, do you know why?

My config file:

```yaml
on:
  push:
    tags:
      - "v*"

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          # A PR will be sent to github.com/Homebrew/homebrew-core to update this formula:
          formula-name: amfora
          download-url: https://github.com/makeworld-the-better-one/amfora.git
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_TOKEN }}
```

Output from failed job:

![image](https://user-images.githubusercontent.com/25111343/145309002-60e30c35-d16e-4a3f-8478-1cb1897ef6fc.png)
