### ISSUE TITLE
POST to refs endpoint results in a 404

### ISSUE THREAD

**Issue by mislav** [mislav/bump-homebrew-formula-action#23]
```yaml
on:
  push:
    tags:
      - "v*"

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-name: amfora
          download-url: https://github.com/makeworld-the-better-one/amfora.git
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_TOKEN }}
```

Output from failed job:

![image](https://user-images.githubusercontent.com/25111343/145309002-60e30c35-d16e-4a3f-8478-1cb1897ef6fc.png)

_Originally posted by @makeworld-the-better-one in https://github.com/mislav/bump-homebrew-formula-action/issues/22#issuecomment-989318626_
