### ISSUE TITLE
Support for on_intel / on_arm syntax in Casks with platform-specific URLs and SHA256

### ISSUE THREAD

**Issue by edospadoni** [mislav/bump-homebrew-formula-action#231]
Hi 👋 first of all, thank you for this great GitHub Action — it’s incredibly useful and well designed!

I’d like to request support for a Cask structure that uses [on_intel / on_arm](https://docs.brew.sh/Cask-Cookbook#handling-different-system-configurations) blocks, like this:

```ruby
cask "<cask_name>" do
  version "1.1.1"

  on_intel do
    sha256 "..."
    url "https://github.com/OWNER/REPO/releases/download/v#{version}/<cask_name>-#{version}-x64.dmg"
  end

  on_arm do
    sha256 "..."
    url "https://github.com/OWNER/REPO/releases/download/v#{version}/<cask_name>-#{version}-arm64.dmg"
  end

  # ...
end
```

or

```ruby
cask "<cask_name>" do
  arch arm: "arm64", intel: "x64"
  version "1.1.1"

  sha256 arm:   "<sha_256_arm>",
         intel: "<sha_256_intel>"

  url "https://github.com/OWNER/REPO/releases/download/v#{version}/<cask_name>-#{version}-#{arch}.dmg"

  # ...
end
```

Ideally, the GitHub Action could support a usage like:

```yaml
- uses: mislav/bump-homebrew-formula-action@v3
  with:
    formula-name: <cask_name>
    formula-path: Casks/n/<cask_name>.rb
    homebrew-tap: Homebrew/homebrew-cask
    tag-name: ${{ env.VERSION }}
    download-url: https://github.com/OWNER/REPO/releases/download/v${{ env.VERSION }}/<cask_name>-${{ env.VERSION }}-{{ env.ARCH }}.dmg
    arch:
      - x64
      - arm64
```

or something like that.

Do you think this would be feasible? I’d be happy to test or help if needed.

Thanks again!
