### ISSUE TITLE
Runs take many hours to complete, despite working

### ISSUE THREAD

**Issue by philwinder** [mislav/bump-homebrew-formula-action#243]
Despite this action working perfectly, whenever I run it, it takes hours to complete.

Do you have any suggestions if I am doing anything wrong?

Code:
https://github.com/helixml/kodit/blob/main/.github/workflows/pypi.yaml#L52

```yaml
      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: ${{ github.event.repository.name }}
          formula-path: Formula/${{ github.event.repository.name }}.rb
          homebrew-tap: ${{ github.repository_owner }}/homebrew-${{ github.event.repository.name }}
          tag-name: "${{ github.event.release.tag_name }}"
          download-url: "https://pypi.org/packages/source/k/${{ github.event.repository.name }}/${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.tar.gz"
          commit-message: |
            {{formulaName}} {{version}}
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
```

Example run:

https://github.com/helixml/kodit/actions/runs/15333442745/job/43175809766
