### ISSUE TITLE
SyntaxError: Unexpected token '.' with v1.14

### ISSUE THREAD

**Issue by hendrikmaus** [mislav/bump-homebrew-formula-action#25]
Version used:
```
Download action repository 'mislav/bump-homebrew-formula-action@v1' (SHA:968f27714be44651974c569409c672531acb5138)
```

Error logged:
```
/home/runner/work/_actions/mislav/bump-homebrew-formula-action/v1/lib/index.js:8334
                if (options?.logRequests === false)
                            ^

SyntaxError: Unexpected token '.'
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```

Used as:
```yaml
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-name: ${{ env.PROJ_NAME }}
          formula-path: Formula/${{ env.PROJ_NAME }}.rb
          homebrew-tap: hendrikmaus/homebrew-tap
          base-branch: main
          # e.g. https://github.com/hendrikmaus/rust-workflows/archive/refs/tags/v0.3.1.tar.gz
          download-url: https://github.com/${{ github.repository }}/archive/${{ github.ref }}.tar.gz
          create-pullrequest: true
          commit-message: |
            {{formulaName}} {{version}}
            
            Created by https://github.com/mislav/bump-homebrew-formula-action, 
            from a workflow based on https://github.com/hendrikmaus/rust-workflows
        env:
          # Assuming your tap repo is public, create a PAT with public_repo scope
          #   see: https://github.com/mislav/bump-homebrew-formula-action
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_COMMIT_TOKEN }}
```

Failed run: https://github.com/hendrikmaus/rust-workflows/runs/4620967721?check_suite_focus=true
