### ISSUE TITLE
How to update Formula in the current repo?

### ISSUE THREAD

**Issue by andrii-bodnar** [mislav/bump-homebrew-formula-action#43]
I am trying to set up a workflow that should update Formula in the current repository.

My workflow:

```yml
name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The new version number (in 3.x.x format)'
        required: true

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest

    steps:
      - uses: mislav/bump-homebrew-formula-action@v2
        with:
          create-pullrequest: false
          formula-path: Formula/crowdin@3.rb
          tag-name: ${{ github.event.inputs.version }}
          download-url: https://downloads.crowdin.com/cli/v3/crowdin-cli-${{ github.event.inputs.version }}.zip
          homebrew-tap: crowdin/homebrew-crowdin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

But I get an error:

```
GET /repos/crowdin/homebrew-crowdin - 401 in 62ms
Error: HttpError: Bad credentials
```

Tried to specify permissions but with no success:

```yml
permissions:
  contents: write
```

Repository for reference: https://github.com/crowdin/homebrew-crowdin
